### ISSUE TITLE
[2.34] Bugs and fixes in the FlxU random generation code

### ISSUE THREAD

**Issue by syndrome** [AdamAtomic/flixel#72]
The current LCG implementation will sometimes throw a negative number as a result, which is undesireable.

Please, follow this link for more information
http://flixel.org/forums/index.php?topic=1611.0

**Comment by AdamAtomic** [comment]
so will the generator actually throw a non 0-1 value, or will the seed just get one assigned?  it should be ok for the seed to have pretty much any value

**Comment by syndrome** [comment]
it may throw an out-of-range number (including the negative numbers!), and the bug is reproduced by using an out-of-range seed number.

that's bad for many reasons, but mainly because in the procedural generation the first generation value is often used as a seed for the second, so if something's wrong things get out of hand pretty soon.

if you follow the link, you'll find the necessary adjustments to the code (and an explanation). this doesn't prevent the users to use any seed value on input, it just makes sure that the seed number is internally compatible with the generator (by permanently fixing the input number).

the seed is supposed to represent floating point bit saturation (meaning it's in 0-1 range), and you'll find an additional little converter I wrote, so that any real number is automatically saturated on input.

I've thoroughly tested the changes (provided in the link above), and they're consistent with the current Flixel interface (that one additional function is private).

(I'm the guy who contributed the original Flixel's LCG function.)

**Comment by AdamAtomic** [comment]
aah ok, i'll try and get it into tonight's build!  thanks :)

**Comment by AdamAtomic** [comment]
Here is the function I put together:

<pre>       static public function fixSeed(Seed:Number):Number
        {
            if(Seed == 0)
                Seed = Number.MIN_VALUE;
            if(Seed >= 1)
            {
                if((Seed%1) == 0)
                    Seed /= Math.PI;
                Seed %= 1;
            }
            else if(Seed < 0)
                Seed = (Seed % 1) + 1;
            return Seed;
        }</pre>


That /= PI bit is to ensure that whole numbers don't all get set to Number.MINVALUE, hopefully it won't mess up the randomness!  Pushing this up to beta and dev in a few minutes...

**Comment by syndrome** [comment]
I'm not sure if this is a good idea.

First of all, fixing the seed is really an internal thing for the LCG algorithm.

Users should not call it just in order to get LCG working properly. In fact, I think many people will just think this is something way too complex, and prefer Math.random instead.

Some other people might oversee fixSeed function which will make their code render degenerate random streams (yet again, they will use Math.random, because noone wants to bother with internal mechanics of a random number generator).

The other thing is, well, I don't think this works actually.

Here's the _getSaturatedSeed function I proposed:

<pre><code>static private function _getSaturizedSeed(Seed:Number):Number
{
  if(Seed < 0 || Seed > 1) Seed %= 1;
  if(Seed < 0) Seed += 1;
  if(Seed == 0) Seed = Number.MIN_VALUE;
  return Seed;
}</code></pre>


This is the line by line explanation:

Because we don't want the seed to exceed the range 0-1, we need this line:

<pre>if(Seed < 0 || Seed > 1) Seed %= 1;</pre>


So for an input 14.567 we get 0.567 as a result.
This works for negative (less than zero) numbers as well, although these will remain negative (which is clearly unwanted). For example, -14.567 yields -0.567 as a result.

We now know that even if we have a negative number at this point, it cannot be less than -0.99999999, so we can get rid of minus by adding 1. At the same time, it's clear that the number can't get greater than 0.999999999.

<pre>if(Seed < 0) Seed += 1;</pre>


The number is now in range.
Finally, and that's only because we need at least some of the bits set for the LCG function to work, we'll substitute 0 with Number.MIN_VALUE. It might seem like a hack, but it really doesn't matter.

The seed is really some rather unimportant value from which the next generation random value is generated. If anyone cares about that particular value from which the entire number sequence originated, he might keep that value somewhere safe in a coding environment external to flixel.

You really don't have to keep that value in flixel. Even if you do (you used the _originalSeed variable, which is ok), the checked, modified, and LCG-compatible value is just fine. After all, if you use that same value, the same sequence of numbers will emerge, so there's no error.

About the whole numbers and the PI value...
There's about a 1:1000000 chance the seed might become a whole number, just by accident (and that's only 0, 1 should never occur, as it never does by using Math.random). Regardless, delimiting by PI won't make a different seed. It's just divided by PI. If a user passes two integers, say 6 and 8, both will be MIN_VALUE / Math.PI, which is basically the same seed over and over.

edit
Oh, I think I see now what you've meant by dividing by PI.
Yeah, not a bad workaround. But look at the end of this comment for yet another approach.
/edit

What's really important are the bits in the memory, not the general appearance of the number. Because of the floating point information, 0-1 is not that small a range to pick from. MIN_VALUE, MIN_VALUE+0.0000001, 0.2, 0.22, 0.226, 0.634, 0.6341, 0.63414938423, and 0.911 are all different seed numbers, each of them capable of starting number sequences which share nothing in common.

The changes I've shown in the flixel forum thread will suffice. Nothing changes in the FlxU interface and everything will behave the same as you planned before. No harm's done, it's just fixed for good.

I know these things, you'll just have to trust me.

Once again, here's what needs changing:

FlxU.seed setter

<pre><code>static public function set seed(Seed:Number):void
{
  _seed = _getSaturizedSeed(Seed);
  _originalSeed = _seed;
}</code></pre>


FlxU.mutate method (a really nice idea, and this is the proper way to do it)

<pre><code>static public function mutate(Seed:Number,Mutator:Number):Number
{
  return _getSaturizedSeed(Seed + Mutator);
}</code></pre>


FlxU.random method (*\* see below) 

<pre><code>static public function random(UseGlobalSeed:Boolean=true):Number
{
  if(UseGlobalSeed && !isNaN(_seed))
  {
    var random:Number = randomize(_seed);
    _seed = _getSaturizedSeed(random);
    return random;
  }
  else
    return Math.random();
}</code></pre>


*\* The seed number is already mutated by assigning the next-generation random value to it, so it doesn't need any kind of additional mutation. This is the preferred way of generating sequences.

Basically you just throw in a seed, and start calling the FlxU.random function. Each subsequent value is based on the previous one, but with LCG applied to it. LCG only is sufficient for this makeover to happen. After all, that's its job.

A random number sequence is generally an array of seed numbers. Pick any value from this array, and you'll be able to regenerate all the values that come after it, just by revolving (recycling) the output value.

And finally, for those three functions to work, you need the private 'fixer' function, because all three of them call it.

<pre><code>static private function _getSaturizedSeed(Seed:Number):Number
{
  if(Seed < 0 || Seed > 1) Seed %= 1;
  if(Seed < 0) Seed += 1;
  if(Seed == 0) Seed = Number.MIN_VALUE;
  return Seed;
}</code></pre>


REALLY IMPORTANT:
If you'd like to allow users to provide larger-than-one real or integer numbers as seeds, with a lesser chance of repeated number sequences, take this function into consideration:

<pre><code>static private function _getSaturizedSeed(Seed:Number):Number
{
  const LIMIT:Number = (1 << 24);
  if(Seed < 0) Seed = -Seed;
  if(Seed >= LIMIT - 1) Seed %= LIMIT - 1;
  if(Seed > 1) Seed /= LIMIT;
  if(Seed == 0) Seed = Number.MIN_VALUE;
  return Seed;
}</code></pre>


This will take care that Seed doesn't exceed the (arbitrary) limit at 2^24 - 1, by warping the value around if it does (thus, 2^24-1+1015 becomes 1015). Next, if it's still larger than 1, it calculates the ratio between the current value and the limit (essentially, a fill percentage). So for 1015, our seed value is calculated as 1015 / LIMIT which gets truncated in AS3 to 0.000060498714447021484 (only three decimals shorter than the real thing). Any negative numbers are dealt with beforehand.

This way, a user could set the seed like this:

<pre><code>FlxU.seed = 124987;</code></pre>


and still get pretty random stuff (in comparison to other similar whole seed numbers), although a whole number was used.

Anyway, people should be encouraged to use seeds in the 0-1 range.

**Comment by syndrome** [comment]
oops I've broken the code markup somehow.
I'm stupid

edit:
fixed now

btw, if I sound harsh, or I wrote something not quite comprehensible, it's early in the morning over here, and I'm getting a little fuzzy.

I'm hopeful you'll understand at least 50% of what I wrote :)

**Comment by AdamAtomic** [comment]
haha no problem, thanks for the extra info.  next update i will change the fixSeed() call to use that wraparound function instead!

I kind of agree with the basic issue of whether or not that thing is even remotely necessary, i mean the built-in global seed...it seemed like a good idea but the organization and use of it is trouble for me, i'll have to think about it!

**Comment by AdamAtomic** [comment]
random number generation has changed/simplified some in the latest (v2.50) so hopefully this is no longer an issue!  let me know if its still a problem
